[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  SKIP_LINT = "true"
  DISABLE_ESLINT_PLUGIN = "true"
  ESLINT_NO_DEV_ERRORS = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Prevent redirect loops
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200